[package]
name = "test_B"
version = "0.1.0"
authors = ["admin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geiger = "0.4.5"
rand = "0.5.1"
walkdir = "2"
cargo-geiger-serde = "0.2.0"